volumes:
  dump_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mine/dump"

  configs_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mine/configs"

  packages_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mine/packages"

  dot_intermine_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mine/intermine"

  mine_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/mine/${MINE_NAME}"

  postgres_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/postgres"

  solr_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./data/solr"

services:
  intermine_builder:
    container_name: intermine_builder
    build:
      context: ./intermine_builder
      dockerfile: ./intermine_builder.Dockerfile
      args:
        - USER_ID=${DOCKER_UID}
        - GROUP_ID=${DOCKER_GID}
    volumes:
      - dump_volume:/home/intermine/intermine/dump
      - configs_volume:/home/intermine/intermine/configs
      - packages_volume:/home/intermine/.m2
      - dot_intermine_volume:/home/intermine/.intermine
      - mine_volume:/home/intermine/intermine/${MINE_NAME}
    environment:
      - MINE_NAME=${MINE_NAME}
      - MINE_REPO_URL=${MINE_REPO_URL}
      - IM_DATA_DIR=${IM_DATA_DIR}
      - MEM_OPTS=${MEM_OPTS}
      - IM_REPO_URL=${IM_REPO_URL}
      - IM_REPO_BRANCH=${IM_REPO_BRANCH}
    depends_on:
      - postgres
      - solr
      - tomcat

  postgres:
    container_name: intermine_postgres
    build:
      context: ./postgres
      dockerfile: ./postgres.Dockerfile
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  solr:
    container_name: intermine_solr
    build:
      context: ./solr
      dockerfile: ./solr.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS}
      - MINE_NAME=${MINE_NAME}
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - solr_volume:/var/solr

  tomcat:
    container_name: intermine_tomcat
    build:
      context: ./tomcat
      dockerfile: ./tomcat.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS}
    ports:
      - ${TOMCAT_HOST_PORT}:${TOMCAT_PORT}
