---
# yamllint disable rule:line-length
name: Docker
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '.github/workflows/docker.yml'
            - 'intermine_builder/**'
            - 'local.docker-compose.yml'
            - 'mkdatadirs.sh'
            - 'postgres/**'
            - 'solr/**'
            - 'tomcat/**'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build
              run: |
                  set -eux -o pipefail
                  sudo apt -y install wait-for-it
                  ./mkdatadirs.sh local.docker-compose.yml
                  DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) docker compose -f local.docker-compose.yml up --build -d
                  wait-for-it localhost:9999 --timeout=300
                  DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) docker compose -f local.docker-compose.yml logs
                  curl -I -L --retry 10 --fail --insecure "http://localhost:9999/biotestmine/"
